### ISSUE TITLE
Can I load other models on huggingface to use this nice tool please?

### ISSUE THREAD

**Issue by WCSY-YG** [spcl/graph-of-thoughts#22]
i'd like to use qwen model to perform GoT reasoning，thank you

**Comment by nblach** [comment]
Hi @WCSY-YG,

In theory, you can use any model with GoT.
We show how you can use models hosted on HuggingFace (HF) at the example of Llama2: https://github.com/spcl/graph-of-thoughts/blob/f508aef4fdfa94adc505f5a7745e6088bdf7889c/graph_of_thoughts/language_models/llamachat_hf.py
If you want to use a different HF model, you should only need to change the `hf_model_id` in the configurations as it uses AutoTokenizer and AutoModel. However, we currently always quantise, which you would need to update if this is not supported/wanted.
Hope that helps!
