### ISSUE TITLE
thanks for the cite, much appreciated

### ISSUE THREAD

**Issue by qrdlgit** [spcl/graph-of-thoughts#3]
It's always great to see a lack of ego and respect for others in academia.

**Comment by nblach** [comment]
Hi qrdlgit,

We checked your profile and saw that you have a repository with the same name, but fail to see how our works relate beyond the common base (ToT).

You are applying ToT-BFS with a branching factor of 3 and customisable depth to improve an ML program, whereby the scoring function reports the achieved r2 score.

This does not intersect with our work, as we are providing a general framework that improves upon ToT with novel ideas and does not cover the automatic improvement of an ML program.

Nevertheless, we'll be happy to acknowledge your work in our paper - please send us a reference to be included (is there a corresponding paper/draft, or shall we just cite your repo?).

**Comment by qrdlgit** [comment]
In general, citing git repos is pretty standard in papers these days.

The approach I take is almost exactly what your paper does, except that I published the repo 4 months ago. 

Honestly, I'm less concerned about the lack of cite to my stuff, but rather the fact that a lot of papers only cite if there is latex behind it.  A lot of ideas I see in arxiv these days are derivative of stuff already in the ecosystem.
