### ISSUE TITLE
huggingface pipeline compatibility

### ISSUE THREAD

**Issue by icecoldt369** [spcl/graph-of-thoughts#6]
hi! this is great work and super interesting!! - looking to experiment and implement this approach using the llama-2 huggingface api. I was wondering if there is a sample implementation as i'm struggling to import the library, therefore need to rely on locally defining it on my cloud notebook. 

This is my training loop if that helps (it's not generating a response, i believe it's not connecting to the api)
```
import json

prompter = SortingPrompter()

# Access the got_merge_prompt attribute
merge_prompt = prompter.got_merge_prompt

# Create an instance of Controller with the SortingPrompter's merge_prompt
controller = Controller(lm, graph, merge_prompt, parse)



# Initialize an empty list to store the generated responses
generated_responses = []

# Set the save frequency and the number of epochs
save_frequency = 5
num_epochs = 1

for epoch in range(num_epochs): 
    for data_point in known_data["examples"]: 
        prompts = data_point['input'].split('\n') 
        for prompt in prompts: 
            response = controller.run(prompt) 
            
            print(f"Instruction: {prompt}") 
            print(f"Response: {response}")

            # Append the response to the list
            generated_responses.append(response)

            # Check if it's time to save the responses
            if len(generated_responses) % save_frequency == 0:
                # Save the responses to a file (e.g., JSON)
                with open('known-got.json', 'w') as json_file:
                    json.dump(generated_responses, json_file)

# Save the responses to a final JSON file after all epochs are done
with open('known-got.json', 'w') as json_file:
    json.dump(generated_responses, json_file)
```

Thanks again!

**Comment by aleskubicek** [comment]
We currently support the following LLMs:
- [OpenAI models](https://github.com/spcl/graph-of-thoughts/blob/main/graph_of_thoughts/controller/chatgpt.py) - API access
- [Llama-2](https://github.com/spcl/graph-of-thoughts/blob/main/graph_of_thoughts/controller/llamachat_hf.py) - local inference (Hugging Face Transformers)

Overview of the LLM instantiation and configuration for both models can be found in the controller [README](https://github.com/spcl/graph-of-thoughts/tree/main/graph_of_thoughts/controller). If you would like to use a different LLM, such as Llama-2 hosted remotely and run the inference using Hugging Face Inference API, you will need to create a new implementation of the [AbstractLanguageModel](https://github.com/spcl/graph-of-thoughts/blob/main/graph_of_thoughts/controller/abstract_language_model.py). Please refer to the [Adding LLMs](https://github.com/spcl/graph-of-thoughts/tree/main/graph_of_thoughts/controller#adding-llms) section of the controller README and to both of our provided implementations (`chatgpt.py` and `llamachat_hf.py`) for further details. 

Finally, to test a simple query, it is enough to instantiate the language model and call the `query` method. To create and run Graph of Operations please refer to our [Quick Start](https://github.com/spcl/graph-of-thoughts/tree/main#quick-start) guide.

We noticed that there were some missing dependencies for running the local Llama-2 model and fixed that in the linked PR. Please let us know if anything is still unclear!
