### ISSUE TITLE
Question about backtracking and looping over thoughts in GoT

### ISSUE THREAD

**Issue by FruVirus** [spcl/graph-of-thoughts#8]
Hi there,

First of all, great work on implementing GoT and the publication of your paper---really appreciate you guys making your source code publicly available!

1. I have a question regarding how one implements backtracking procedures in the Graph of Operations? Technically, you cannot do this (otherwise it wouldn't be a DAG). Thus, is the idea that you define all possible paths and then have `Operation`s effectively halt their execution for paths that fail to meet some criteria?
2. Second question is regarding looping over thoughts. How does one refine a single `Operation`? Or does the paper only mean that one can refine over `Thought`s and not `Operation`s?

**Comment by nblach** [comment]
Hi @FruVirus,

Thanks for your kind words and for taking an interest in our project!

1. You are correct. At this point in time, the GoO is a DAG (+ self-loops) constructed statically before execution. This means that you would have to define the paths you want to explore before execution and utilise filtering operations to remove paths that are not worth exploring further (generally, with some small exceptions, an operation with no previous thoughts will not perform any work).
2. I am not sure what you mean with refining an operation. Operations deal with processing thoughts. When we talk about "refinement", we mean improving thoughts, not the actions themselves. Check out the [`ValidateAndImprove` Operation](https://github.com/spcl/graph-of-thoughts/blob/f6be6c06f22728afd22b2a19eca1cfa27010dcf0/graph_of_thoughts/operations/operations.py#L269). For each thought of the previous operations, it tries to improve the thought until it is valid (or the number of tries reaches the limit). You could implement a similar operation quite easily for continuous refinements until a certain score is reached. 

I hope this clears things up! Let me know if you have more questions.

**Comment by kripper** [comment]
Is the path generation still static (done before execution)?
This sounds very limiting.
Any plans to improve?

**Comment by kripper** [comment]
Here is a dynamic GoT implementation of your code:
https://github.com/JayceNing/DGoT/blob/a0c364ad94bd4110c83485cd50f2e4ea7bbba9a5/graph_of_thoughts/operations/operations.py#L482

The repo also links to a paper.

Consider merging.
