### ISSUE TITLE
Possible error in `got` method for `doc_merge.py`

### ISSUE THREAD

**Issue by FruVirus** [spcl/graph-of-thoughts#9]
https://github.com/spcl/graph-of-thoughts/blob/f6be6c06f22728afd22b2a19eca1cfa27010dcf0/examples/doc_merge/doc_merge.py#L223C45-L223C45

In the line above, if `current` is either `None` or an empty string, should the string formatting be `num=len(documents)` instead?

**Comment by nblach** [comment]
Thank you, great catch!
You are correct that it should be `num=len(documents)` for the `got` approach, but not for the `got2` approach.
